/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmddesdejava;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlos
 */
public class GrupoOpciones extends javax.swing.JFrame {

    /**
     * Creates new form GrupoOpciones
     */
    public GrupoOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnNewGroup = new javax.swing.JButton();
        jBtnModifGroup = new javax.swing.JButton();
        jBtnElimGroup = new javax.swing.JButton();
        jBtnListaGroup = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Opciones ");

        jBtnNewGroup.setText("Nuevo Grupo");
        jBtnNewGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewGroupActionPerformed(evt);
            }
        });

        jBtnModifGroup.setText("Modificar Grupo");
        jBtnModifGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifGroupActionPerformed(evt);
            }
        });

        jBtnElimGroup.setText("Eliminar GRupo");
        jBtnElimGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElimGroupActionPerformed(evt);
            }
        });

        jBtnListaGroup.setText("Lista Grupos");
        jBtnListaGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListaGroupActionPerformed(evt);
            }
        });

        jBtnRegresar.setText("Regresar");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBtnNewGroup)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnModifGroup)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElimGroup)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnListaGroup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jBtnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNewGroup)
                    .addComponent(jBtnModifGroup)
                    .addComponent(jBtnElimGroup)
                    .addComponent(jBtnListaGroup))
                .addGap(18, 18, 18)
                .addComponent(jBtnRegresar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        Usuario principal = null;
        try {
            principal = new Usuario();
        } catch (IOException ex) {
            Logger.getLogger(GrupoOpciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBtnListaGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListaGroupActionPerformed
         ListaGrupos2 opciones= new ListaGrupos2();
        opciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnListaGroupActionPerformed

    private void jBtnElimGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElimGroupActionPerformed
       EliminarGrupo opciones= new EliminarGrupo();
        opciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnElimGroupActionPerformed

    private void jBtnModifGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifGroupActionPerformed
        ModificarGrupo opciones= new ModificarGrupo();
        opciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnModifGroupActionPerformed

    private void jBtnNewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewGroupActionPerformed
         GrupoNuevo opciones= new GrupoNuevo();
        opciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnNewGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupoOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupoOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupoOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupoOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupoOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElimGroup;
    private javax.swing.JButton jBtnListaGroup;
    private javax.swing.JButton jBtnModifGroup;
    private javax.swing.JButton jBtnNewGroup;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
